#!/bin/sh

################################################################################

SCRIPT_DIR=$(dirname "$(readlink --canonicalize "$(which "$0")")")
. "$SCRIPT_DIR/../common.sh"

################################################################################

repository=./repository

usage()
{
	cat <<EOF
Usage: $COMMAND [--repository=<repository>] <recipe>...

Builds package(s) from <recipe>(s) to <repository>.

<repository>    The path of the directory where to put the built packages.
<recipe>        The path of a directory containing a package's recipe (default is
                “$repository”).
EOF
}

for arg
do
	case "$arg" in
		'--help'|'-h')
			usage
			return
			;;
		'--repository='*)
			repository=${arg#'--repository='}
			shift
			;;
		-*)
			psl_fatal "Invalid option “$arg”. Try $COMMAND --help"
			;;
		*)
			break
	esac
done

if [ $# -eq 0 ]
then
	psl_fatal 'missing <recipe>(s)'
fi

for psl
do
	psl_realpath

	build "$psl" "$repository"
done
