#!/bin/sh

################################################################################

SCRIPT_DIR=$(dirname "$(readlink --canonicalize "$(which "$0")")")
. "$SCRIPT_DIR/../common.sh"

################################################################################

repository=./repository

usage()
{
	cat <<EOF
Usage: $0 --help
       $0 [--repository=REPOSITORY] RECIPE...

Builds package(s) from RECIPE(s) to REPOSITORY.

--help        Prints this help message

REPOSITORY    The path of the directory where to put the built packages.

RECIPE        The path of a directory containing a package's recipe (default is
              “$repository”).
EOF
}

for arg
do
	case "$arg" in
		'--help'|'-h')
			usage
			return
			;;
		'--repository='*)
			repository=${arg#'--repository='}
			shift
			;;
		-*)
			psl_fatal "Invalid option “$arg”. Try $0 --help"
			;;
		*)
			break
	esac
done

if [ $# -eq 0 ]
then
	psl_fatal 'missing RECIPE(s)'
fi

if ! [ -d "$repository" ]
then
	psl_fatal "this is not a valid repository: $repository"
fi

psl=$repository; psl_realpath; repository=$psl

for psl
do
	psl_realpath

	build "$psl" "$repository"
done
