#!/bin/sh

################################################################################

SCRIPT_DIR=$(dirname "$(readlink --canonicalize "$(which "$0")")")
. "$SCRIPT_DIR/../common.sh"

################################################################################

if [ $# -lt 2 ]
then
	cat <<EOF >&2
Usage: $0 --help
       $0 REPOSITORY RECIPE...

Builds package(s) from RECIPE(s) to REPOSITORY.

--help        Prints this help message

REPOSITORY    The path of the directory where to put the built packages.

RECIPE        The path of a directory containing a package's recipe.
EOF
	exit 1
fi

psl=$1; psl_realpath; repository=$psl; shift

for psl
do
	psl_realpath

	build "$psl" "$repository"
done
