#!/bin/sh

################################################################################

SCRIPT_DIR=$(dirname "$(readlink --canonicalize "$(which "$0")")")
. "$SCRIPT_DIR/../common.sh"

################################################################################

repository=.

usage()
{
	cat <<EOF
Usage: $COMMAND [--repository=<repository>]

Scans <repository> and creates the “Packages.gz” index file.

<repository>    The path of the directory to scan for changes (default is
                “$repository”).
EOF
}

for arg
do
	case "$arg" in
		'--help'|'-h')
			usage
			return
			;;
		'--repository='*)
			repository=${arg#'--repository='}
			;;
		*)
			psl_fatal "Invalid option “$arg”. Try $COMMAND --help"
	esac
done

if ! [ -d "$repository" ]
then
	psl_fatal "this is not a valid repository: $repository"
fi

refresh "$repository"
